language: cpp
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq flex bison autoconf automake libtool libltdl3-dev libnetsnmp
compiler:
  - clang
  - gcc
script: "./build.sh && ./configure && make && make install"
