language: cpp
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq flex bison autoconf automake libcurl4-openssl-dev libtool libltdl3-dev libsnmp-dev libxml2-dev
compiler:
  - gcc
script: "./build.sh && ./configure && make && make install"
